### ISSUE TITLE
Writing prompts triggers keyboard shortcuts

### ISSUE THREAD

**Issue by zvit** [richrobber2/canvas-zoom#28]
While writing a prompt, the keyboard shortcuts are getting triggered as I type, and the canvas scales and unscales all over the place.

**Comment by daswer123** [comment]
It's weird, it's a mistake, it shouldn't work that way. 

Maybe the mouse was in the image area when typing the prompt

https://user-images.githubusercontent.com/22278673/232237811-517c4fc3-155b-44e6-a8f0-c5dc586fdb28.mp4

**Comment by zvit** [comment]
It doesn't always happen, but I'm sure I am careful to click in the prompt box, and not have the image on mouse focus. However, if I paste text into the prompt box using a custom AHK menu, it ALWAYS makes the canvas go haywire, as you can see in the attached video, it triggered a scale, and it triggered the 'c' - making the paint semi-transparent. 


https://user-images.githubusercontent.com/9898388/232239121-0f60a2c4-cae7-4584-87d7-2bddd5167654.mp4

**Comment by daswer123** [comment]
I see, I have some ideas how to fix it.
Thank you for finding the bug

**Comment by daswer123** [comment]
Bro sorry, but you have a specific case, and if I adjust for you, it will break the behavior for ordinary users.

Everything I've tried to fix your problem leads to others not being comfortable to use.

I can offer you a solution to this problem, in AHK add mouse behavior, so that when you type, it moves away from the image area.
