### ISSUE TITLE
Latest Update : F stays stuck

### ISSUE THREAD

**Issue by hansolocambo** [richrobber2/canvas-zoom#30]
Since the latest update, when I press F to Drag the image in Inpaint, the image keeps paning around even after I released "F". 
Only way to get rid of that is to close the Tab and open a new one. I tried to Ctrl+F5 refresh the page, but the F was still stuck and the image was still moving...

**Comment by daswer123** [comment]
Hi @hansolocambo 

https://user-images.githubusercontent.com/22278673/232739376-2db374eb-d45a-473c-b855-f06472387f2d.mp4

Write what actions lead to this problem. And what browser do you use?

**Comment by Woisek** [comment]
Adding details to this issue: The whole "hold key" thing doesn't work, if users have "Automatically search the page text when typing" activated in their browser. A possible solution maybe would be to use the space bar, like it's learned from other software like Photoshop.

**Comment by daswer123** [comment]
Thank you, as I understand this problem only on firefox, to be honest I do not understand how you can use hotkeys with this mode.

Moving the space bar will cause a lot of problems, since a lot of standard browser actions are tied to it. If I do this, I'll have to override these actions on the whole page, which will cause even more problems for other users.

**Comment by daswer123** [comment]
In the latest update, moving via Mouse+Wheel(hold) works without problem, even with this mod.

**Comment by Woisek** [comment]
>Thank you, as I understand this problem only on firefox, to be honest I do not understand how you can use hotkeys with this mode.

Yes, I talked about Firefox, becasue that's what I'm useing. But other than that, it works surprisingly well.

>Moving the space bar will cause a lot of problems, since a lot of standard browser actions are tied to it.

When I found out, I pressed the spacebar a few times but didn't noticed anything coming in the way. That's why I suggested it. Maybe on a Gradio website, those functions you are talking about, are not applicable ... ?
Again, thanks for this much needed extension. 👍

**Comment by daswer123** [comment]
I just googled this setting and the first thing I found was firefox :)

About the space bar, I have some idea, I think I will try to implement in the near future, but I'm not sure that it will work well.

**Comment by hansolocambo** [comment]
Thanks a lot daswer123 for your always useful advice and quick updates. Sorry I didn't come back before on that thread as I was away from home. 
I'll download the updated version now and, if anything's wrong, I'll come back here ;)
If it's all good I'd say you can close that thread in a day or two. 
Cheers.

**Comment by daswer123** [comment]
I hope you are doing well, if anything, open a new issue
