### ISSUE TITLE
[Issue]: No full image display in inpainting

### ISSUE THREAD

**Issue by Woisek** [richrobber2/canvas-zoom#58]
I do some dual wallpaper generations lately and mostly, I don't need to edit them afterwards. But now I have a few where I'd like to inpaint some elements and noticed, that the image, when drag and dropped into the placeholder, is not fully displayed in the inpainting tab unlike in the img2img tab. It looks like, the element containing the image (id="img2masing") has a overflow: hidden applied. By removing this, the image becomes visible. maybe this switch could be combined with the moving (F key) and reset when resetting.

![Zwischenablagebild](https://github.com/richrobber2/canvas-zoom/assets/122026301/270745d2-27a3-46b0-8b15-0e30161f56df)
![Zwischenablagebild (1)](https://github.com/richrobber2/canvas-zoom/assets/122026301/84cc592f-0a01-46c5-8ab6-d93602b4656d)

Win10, FF106

**Comment by daswer123** [comment]
You can do this by pressing the key combination: first **S** and then **R**
But I'm going to try your idea, and I'll let you know later.

**Comment by Woisek** [comment]
>You can do this by pressing the key combination: first S and then R

Oh ... I totally missed that. 😱 Now that you say it ... yes, I found it. Oh man ... 😔
Thanks for the hint.

>But I'm going to try your idea, and I'll let you know later.

Cool, thanks. 👍

**Comment by daswer123** [comment]
Anyway, I looked at it, and unfortunately it's not a very good solution. Because if you just remove the overflow, the picture that does not fit into the width of the screen will extend beyond the screen.

I'm still testing different options, but in any case, thanks for the idea :)

By the way, you can just press **S** twice and it will be the same as **S** + **R**

**Comment by Woisek** [comment]
OK, thanks! 🙂
