### ISSUE TITLE
.tooltip display: none but .tooltip never used in the extension

### ISSUE THREAD

**Issue by mariodian** [richrobber2/canvas-zoom#67]
Hi, you're setting `.tooltip` to be hidden in `style.css` but that element seems to never be used in your code.

````css
.tooltip{
  display: none;
}
````

However, it [interferes with tooltip in Vlad's Automatic UI](https://github.com/vladmandic/automatic/issues/1377#issuecomment-1589302582). 

Could you please remove the CSS code, if `.tooltip` is in fact never used as far as I can tell? Thank you (I can also create a PR if you want)

**Comment by daswer123** [comment]
Hi, this is to make the "canvas-zoom-and-pan" buildin extension, which comes with webui 1.4, compatible with the "canvas-zoom" extension

A little later I will make a PR in Automatic1111 webui and make this class more specific and change it in my extension code.

I can't completely remove this css property yet, but I can make it more specific. If I make instead of `.tooltip`,  make `.image-container .tooltip` will that solve the problem?

**Comment by daswer123** [comment]
UPD, updated, check to see if that solved your problem, if not, I'll think what else can be done?

**Comment by mariodian** [comment]
It works thank you!
