### ISSUE TITLE
Mobile gesture support

### ISSUE THREAD

**Issue by auguster** [richrobber2/canvas-zoom#81]
Hello,

I'm using stable diffusion webui a lot on my phone and tablet and unfortunately the pinch gesture doesn't work anymore. It's frustrating because I want to inpaint using the touch screen, it's so much easier than the mouth to draw masks. It's also very practical to move around the canvas using zoom in and zoom out.

Also, on mobile, the UI button seems to move with the canvas instead of keeping their position, on large image, the UI get outside the view which is annoying also. This might be caused by the fact that the gesture are not handled as it should.

I remember that it used to work some times ago (but I can't remember when). I'll try to look into the code to maybe propose a PR but I don't know your code yet.

Best regards,

**Comment by daswer123** [comment]
Hi, improved work a bit with canvas, but to me auto1111 doesn't seem very suitable for inpaint on a phone. 

I've updated the code a bit and finalized the setting to add buttons, so that the picture would fit the screen.

Enable this item in the extension settings, then 2 buttons will appear: F - Fullscreen, P - Pippete. 

https://github.com/richrobber2/canvas-zoom/assets/22278673/6d41d943-3b95-48b2-b5fb-3169ba6ecc88

P.S I tested on my phone works better than on the video, since I tested on pc with development tools

**Comment by auguster** [comment]
I've test it out on my mobile and it's better than before but it's not very practical yet. The issue is that when the canvas is zoomed in too much, there is no more things to hang on.

I think I have an idea on the gesture that could be used to really make it good. I have to make some test to see how it works out.

I'll try to find the time to work on it this week to make a pull request.

**Comment by daswer123** [comment]
I realize it's not the best solution :)

I'd welcome any contribution.

**Comment by daswer123** [comment]
Working all day today, no chance to check it out yet. I'll check it at the end of the day or tomorrow, thanks for reporting the problem

**Comment by daswer123** [comment]
@CCpt5 Fixed, this problem shouldn't be there now.

**Comment by daswer123** [comment]
Don't worry, even if it happens only to you, it's still worth checking.
As for hiding buttons, I added another trigger, maybe that will help.
